"""Inference entrypoint for final private evaluation.

Execute `python predict.py --help` to see available command-line parameters.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import tyro

from src.config import get_configuration_id, get_config
from src.datasets import load_dataset, load_schema
from src.predict import predict_for_checkpoint
from src.util import find_last_checkpoint


def load_forecast_index(input_dir: Path) -> pd.DataFrame:
    """Load the rows that need predictions."""
    candidates = [
        input_dir / "forecast_index_test.csv",
        input_dir / "forecast_index_validation.csv",
    ]
    for forecast_index in candidates:
        if forecast_index.exists():
            return pd.read_csv(forecast_index)
    expected = ", ".join(path.name for path in candidates)
    raise FileNotFoundError(f"Expected one of {expected} in input_dir.")


def do_predict(checkpoint: Path | None = None, input_dir: Path = Path("dataset"),
               output_file: Path | None = None):
    """
    Run the given model on the given dataset and write predictions to the csv file.
    Args:
        checkpoint:  path to the checkpoint to use. If omitted, the most recent checkpoint from the `logs` directory is used.
        input_dir:   path to the dataset.
        output_file: output file for the predictions.
                     If omitted, output is written to the `predictions` directory with an autogenerated file name.
    """
    if checkpoint is None:
        checkpoint = find_last_checkpoint()

    if checkpoint is None or not checkpoint.exists():
        raise FileNotFoundError(f"Missing checkpoint: {checkpoint}")

    config = get_config(checkpoint)

    train_df = load_dataset("train", input_dir)
    val_df = load_forecast_index(input_dir)
    schema = load_schema(input_dir)

    model_result = predict_for_checkpoint(checkpoint, config, train_df, val_df, schema)

    if output_file is None:
        output_file = Path(os.path.join("predictions", get_configuration_id(config) + ".csv"))
    output_file.parent.mkdir(parents=True, exist_ok=True)
    model_result.to_csv(output_file, index=False)
    print(f"Written predictions to {output_file}")


if __name__ == "__main__":
    tyro.cli(do_predict, use_underscores=True)
