"""Inference entrypoint for final private evaluation.

Execute `python predict.py --help` to see available command-line parameters.
"""

from __future__ import annotations

import os
from pathlib import Path

import tyro

from src.datasets import load_dataset, load_schema, preprocess_dataset, load_forecast_index
from src.model_registry import create_model, get_config
from src.predict import predict
from src.train import load_model
from src.util.util import find_last_checkpoint, pick_device


def do_predict(checkpoint: Path | None = None, input_dir: Path = Path("dataset"),
               output_file: Path | None = None):
    """
    Run the given model on the given dataset and write predictions to the csv file.
    Args:
        checkpoint:  path to the checkpoint to use. If omitted, the most recent checkpoint from the `logs` directory is used.
        input_dir:   path to the dataset.
        output_file: output file for the predictions.
                     If omitted, output is written to the `predictions` directory with an autogenerated file name.
    """
    if checkpoint is None:
        checkpoint = find_last_checkpoint()
        print(f"Using checkpoint {checkpoint}")

    if checkpoint is None or not checkpoint.exists():
        raise FileNotFoundError(f"Missing checkpoint: {checkpoint}")

    context_df = load_dataset("train", input_dir)
    forecast_df = load_forecast_index(input_dir)
    schema = load_schema(input_dir)

    preprocess_dataset(context_df, schema)

    config = get_config(checkpoint)
    print(f"Using model config {config}")

    device = pick_device()
    print(f"Using device {device}")

    model = create_model(config, schema).to(device)
    load_model(checkpoint, model, device=device)
    model.eval()

    prediction_result = predict(model, context_df, forecast_df, schema,
                                config.context_size, config.prediction_horizon, device=device)

    if output_file is None:
        output_file = Path(os.path.join("predictions", config.get_id() + ".csv"))
    output_file.parent.mkdir(parents=True, exist_ok=True)
    prediction_result.to_csv(output_file, index=False)
    print(f"Written predictions to {output_file}")


if __name__ == "__main__":
    tyro.cli(do_predict, use_underscores=True)
